export type categories = {
  "General Knowledge": 9,
  "Entertainment: Books": 10,
  "Entertainment: Film": 11,
  "Entertainment: Music": 12,
  "Entertainment: Musicals & Theatres": 13,
  "Entertainment: Television": 14,
  "Entertainment: Video Games": 15,
  "Entertainment: Board Games": 16,
  "Science & Nature": 17,
  "Science: Computers": 18,
  "Science: Mathematics": 19,
  "Mythology": 20,
  "Sports": 21,
  "Geography": 22,
  "History": 23,
  "Politics": 24,
  "Art": 25,
  "Celebrities": 26,
  "Animals": 27,
  "Vehicles": 28,
  "Entertainment: Comics": 29,
  "Science: Gadgets": 30,
  "Entertainment: Japanese Anime & Manga": 31,
  "Entertainment: Cartoon & Animations": 32,
}

export enum Categories {
  General_Knowledge = 9,
  Entertainment_Books = 10,
  Entertainment_Film = 11,
  Entertainment_Music = 12,
  Entertainment_Musicals_Theatres = 13,
  Entertainment_Television = 14,
  Entertainment_Video_Games = 15,
  Entertainment_Board_Games = 16,
  Science_Nature = 17,
  Science_Computers = 18,
  Science_Mathematics = 19,
  Mythology = 20,
  Sports = 21,
  Geography = 22,
  History_ = 23,
  Politics = 24,
  Art = 25,
  Celebrities = 26,
  Animals = 27,
  Vehicles = 28,
  Entertainment_Comics = 29,
  Science_Gadgets = 30,
  Entertainment_Japanese_Anime_Manga = 31,
  Entertainment_Cartoon_Animations = 32,
}